package pipeline;

import client.MistralClient;
import generator.TestGenerator;
import parser.JsonExtractor;
import parser.TestcasesParser;
import security.PiiMasker;
import security.PiiReport;
import security.PiiScanner;
import util.FilesUtil;
import util.TestRunExecutor;

public class PipelineMain {

    private static final String CHECKLIST_PATH = "checklist_login.txt";
    private static final String TESTCASES_PATH = "generated/testcases.json";

    public static void main(String[] args) {
        System.out.println("=== AI QA PIPELINE STARTED ===");

        String scenariosPrompt = PromptEngine.buildPrompt(
                "prompts/01_scenarios_from_checklist.txt", CHECKLIST_PATH);
        FilesUtil.write("generated/scenarios_prompt.txt", scenariosPrompt);

        PiiReport report = PiiScanner.scan(scenariosPrompt);
        FilesUtil.write("generated/pii_report.txt", report.toText());
        if (report.hasFindings()) {
            System.out.println("PII detected. Masking input.");
            scenariosPrompt = PiiMasker.mask(scenariosPrompt);
            FilesUtil.write("generated/scenarios_prompt_masked.txt", scenariosPrompt);
        }

        MistralClient.LlmResponse scenariosResponse = MistralClient.call(scenariosPrompt);
        FilesUtil.write("generated/scenarios_raw.json", scenariosResponse.rawBody());
        String scenarios = scenariosResponse.content();
        FilesUtil.write("generated/scenarios.txt", scenarios);

        String testcasesPrompt = FilesUtil.read("prompts/02_testcases_json.txt")
                .replace("{{SCENARIOS}}", scenarios);
        FilesUtil.write("generated/testcases_prompt.txt", testcasesPrompt);

        MistralClient.LlmResponse testcasesResponse = MistralClient.call(testcasesPrompt);
        FilesUtil.write("generated/testcases_raw.json", testcasesResponse.rawBody());
        FilesUtil.write("generated/testcases_llm.txt", testcasesResponse.content());

        String testcasesJson = JsonExtractor.extractJson(testcasesResponse.content());
        FilesUtil.write(TESTCASES_PATH, testcasesJson);
        TestcasesParser.parse(TESTCASES_PATH);
        System.out.println("Testcases generated: " + TESTCASES_PATH);

        String generatedTest = TestGenerator.generate(testcasesJson);
        System.out.println("Autotests generated by AI.");

        String testRunLog = TestRunExecutor.runTests();
        FilesUtil.write("generated/test_run.log", testRunLog);
        String allureReportLog = TestRunExecutor.buildAllureReport();
        FilesUtil.write("generated/allure_report.log", allureReportLog);
        String allureResults = FilesUtil.readFilesBySuffix("target/allure-results", "-result.json");
        FilesUtil.write("generated/allure_results.txt", allureResults);

        String bugPrompt = FilesUtil.read("prompts/04_bug_report.txt")
                .replace("{{TEST_RUN_LOG}}", testRunLog)
                .replace("{{ALLURE_RESULTS}}", allureResults);
        FilesUtil.write("generated/bug_report_prompt.txt", bugPrompt);

        MistralClient.LlmResponse bugResponse = MistralClient.call(bugPrompt);
        FilesUtil.write("generated/bug_report_raw.json", bugResponse.rawBody());
        FilesUtil.write("generated/bug_report_llm.txt", bugResponse.content());
        FilesUtil.write("generated/bug_report.json", JsonExtractor.extractJson(bugResponse.content()));

        System.out.println("Bug report saved: generated/bug_report.json");
        System.out.println("=== AI QA PIPELINE FINISHED ===");
    }
}
